import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { PageHero } from "../components/PageHero";

export const metadata: Metadata = { title: "About NUAN | Our Story and Purpose", description: "Learn how NUAN grew from many passions into one meaningful brand built around creativity, learning, stories, and care.", openGraph: { title: "About NUAN | Our Story and Purpose", description: "The story, mission, vision, and values behind NUAN." } };

export default function AboutPage() {
  return <main><PageHero eyebrow="Our story and purpose" title={<>A brand shaped by<br /><em>heart, growth, and faith.</em></>} copy="NUAN is a growing family of creations built from a founder’s love for teaching, storytelling, practical solutions, and thoughtful handmade experiences." />
    <section className="section origin-grid"><div className="origin-art"><Image src="/assets/nuan-logo.png" alt="NUAN by JLEL brand mark" width={560} height={650} /></div><div><p className="section-tag">The birth of NUAN</p><h2>Many passions brought together by one meaningful dream.</h2><p>NUAN began with small ideas: creating learning experiences, writing stories shaped by real life, building tools that make everyday work easier, and preparing sweet treats that bring people together.</p><p>Rather than choosing only one path, NUAN became the home where those passions could grow together. Every branch has its own character, but all are guided by purpose, warmth, and a genuine desire to create something useful or meaningful.</p><blockquote>“This is only the beginning of NUAN’s story—and we are grateful to have you as part of it.”</blockquote></div></section>
    <section className="section journey"><header className="center-heading"><p className="section-tag">Founder’s journey</p><h2>Learning, rebuilding,<br /><em>and creating forward.</em></h2></header><div className="timeline">{[["01","Create","Ideas began through teaching, writing, business, and hands-on creative work."],["02","Learn","Challenges became lessons in discipline, faith, redirection, and resilience."],["03","Bring together","NUAN became the shared name for products, stories, and digital experiences."],["04","Grow with purpose","The journey continues through thoughtful work that serves real people."]].map(([num,title,copy])=><article key={num}><span>{num}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
    <section className="mission-grid"><article><span>Mission</span><h2>To create with meaning.</h2><p>To make thoughtful products, stories, learning experiences, and digital solutions that bring value, encouragement, and joy to everyday life.</p></article><article><span>Vision</span><h2>To grow without losing heart.</h2><p>To become a trusted creative brand where education, business, storytelling, and care come together in ways that remain personal and purposeful.</p></article></section>
    <section className="section values-section"><header className="center-heading"><p className="section-tag">What guides us</p><h2>Wrapped with Blessings,<br /><em>Made with Love.</em></h2></header><div className="values-grid">{[["Thoughtful","Every idea begins with a real purpose and the people it hopes to serve."],["Personal","From stories to sweets, every NUAN experience is made to feel warm and human."],["Growing","Different passions are given room to learn, improve, and become more."],["Faith-led","Redirection and setbacks can become part of a more meaningful path."]].map(([title,copy])=><article key={title}><h3>{title}</h3><p>{copy}</p></article>)}</div><div className="center-actions"><Link className="button" href="/products">Explore NUAN products →</Link><Link className="text-link" href="/contact">Contact us</Link></div></section>
  </main>;
}
