import type { Metadata } from "next";
import Image from "next/image";
import { PageHero } from "../components/PageHero";
import { messenger, products, projects } from "../lib/site-data";

export const metadata: Metadata = { title: "NUAN Products | Pastillas, Books, Games and Trackers", description: "Explore NUAN pastillas, purpose-driven digital books, educational games, and practical digital trackers.", openGraph: { title: "NUAN Products | Pastillas, Books, Games and Trackers", description: "Thoughtful products and digital creations from the NUAN family." } };

function InquiryButton({ label = "Buy or inquire" }: { label?: string }) { return <a className="button" href={messenger} target="_blank" rel="noreferrer">{label} ↗</a>; }

export default function ProductsPage() {
  const pastillas = products.filter((item) => item.category === "Pastillas");
  const books = products.filter((item) => item.category === "Books");
  const games = projects.filter((item) => item.category === "Educational Game");
  const trackers = projects.filter((item) => item.category === "Digital Tracker");
  return <main><PageHero eyebrow="Products and creations" title={<>Thoughtfully made for<br /><em>real moments and needs.</em></>} copy="Browse the NUAN collection by category. Verified prices are shown when available; message us for current availability and order details." actions={<div className="category-pills"><a href="#pastillas">Pastillas</a><a href="#books">Books</a><a href="#games">Games</a><a href="#trackers">Trackers</a></div>} />
    <section className="section product-category" id="pastillas"><header className="section-heading"><div><p className="section-tag">Category A</p><h2>NUAN <em>Pastillas</em></h2></div><p>Individually wrapped milk and ube treats for sharing, gifting, or keeping for your own sweet moments.</p></header><div className="detail-grid two">{pastillas.map((item)=><article className="detail-card" key={item.title}><div className="detail-image soft"><Image src={item.image} alt={item.title} width={800} height={1100} /></div><div><p className="category">{item.category}</p><h3>{item.title}</h3><p>{item.description}</p><ul>{item.details.map((detail)=><li key={detail}>{detail}</li>)}</ul><strong>{item.price}</strong><p className="fine-print">Store sealed in a cool, dry place. Confirm current storage and pickup guidance when ordering.</p><InquiryButton label="Order through Messenger" /></div></article>)}</div></section>
    <section className="section product-category dark-section" id="books"><header className="section-heading"><div><p className="section-tag">Category B</p><h2>NUAN <em>Books</em></h2></div><p>Each title is presented separately so its cover, story, audience, and reading experience remain clear.</p></header><div className="book-detail-list">{books.map((book,index)=><article className="book-detail" key={book.title}><div className="book-cover"><Image src={book.image} alt={`${book.title} book cover`} width={610} height={850} /></div><div><p className="category">Purpose-driven digital book</p><h3>{book.title}</h3><p>{book.description}</p><ul>{book.details.map((detail)=><li key={detail}>{detail}</li>)}</ul><strong>{book.price}</strong><InquiryButton /></div><div className="book-video"><p>Digital book preview</p><video controls playsInline preload="metadata" poster={book.image}><source src={index === 0 ? "/assets/mental-capital-preview.mp4" : "/assets/gift-storm-preview-v3.mp4"} type="video/mp4" /></video><span>Press play to watch the complete preview.</span></div></article>)}</div></section>
    <section className="section product-category" id="games"><header className="section-heading"><div><p className="section-tag">Category C</p><h2>Educational <em>Games</em></h2></div><p>Interactive AP experiences designed to make history and geography feel more active, memorable, and engaging.</p></header><div className="detail-grid two">{games.map((game)=><article className="simple-product" key={game.title}><Image src={game.image} alt={`${game.title} project preview`} width={900} height={600} /><div><p className="category">{game.category}</p><h3>{game.title}</h3><p>{game.description}</p><dl><div><dt>Target learners</dt><dd>{game.audience}</dd></div><div><dt>Status</dt><dd>{game.status}</dd></div></dl><a className="button dark" href="/portfolio">View project details →</a></div></article>)}</div></section>
    <section className="section product-category tracker-section" id="trackers"><header className="section-heading"><div><p className="section-tag">Category D</p><h2>Digital <em>Trackers</em></h2></div><p>Practical digital tools for clearer records, reflection, and day-to-day decision-making on mobile and desktop.</p></header><div className="tracker-grid">{trackers.map((tracker)=><article key={tracker.title}><span>Digital format</span><h3>{tracker.title}</h3><p>{tracker.description}</p><ul><li>{tracker.audience}</li><li>{tracker.tools}</li><li>Mobile, tablet, laptop, and desktop compatible</li></ul><strong>Inquire for current price</strong><InquiryButton /></article>)}</div></section>
    <section className="faq section"><header className="center-heading"><p className="section-tag">Frequently asked</p><h2>Before you order</h2></header><div className="faq-list">{[["How do I place an order?","Use any inquiry button to contact NUAN through Messenger. Include the product, quantity, and preferred pickup or delivery details."],["Are all items always available?","Availability may change. Please confirm current stocks, formats, and fulfillment details before payment."],["Can I use the digital products on my phone?","Most digital books and trackers are designed for phones, tablets, laptops, and desktops. Confirm the specific format when ordering."],["Can NUAN create a custom project?","Yes. Use the Contact page and choose Educational Game, Website Development, or Business System."]].map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></section>
  </main>;
}
